config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|ru/ do
    root to: "blog#home", as: "blog"
  end

  constraints country: /ukraine|usa|united_kingdom|canada|manitoba/ do
    get "/:country/checklist/edit" => "checklist#edit"
    post "/:country/checklist/edit" => "checklist#save"
    scope "(:locale)", locale: /en|ru/ do
      get "/:country" => "countries#gallery", as: "country"
      get "/:country/checklist" => "checklist#show", as: "checklist"
    end
  end

  resources :species, only: [:edit, :update] do
    collection do
      get "admin", action: :index
      get "admin/search", action: :admin_search

      get :review
      get "synonyms" => "synonyms#index"
      patch "synonyms/:id" => "synonyms#update"

      get "splits" => "species_splits#index"
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    resources :species, only: [:show], as: :localized_species do
      get "search", on: :collection
    end
    get "species" => "species#gallery", as: "gallery"
  end

  resources :photos, controller: "images", as: "images", except: [:index, :show] do
    member do
      get "edit/map", action: :map_edit
      post "patch"
    end
    collection do
      post "upload"
    end
  end

  resources :videos, except: [:index, :show] do
    member do
      get "edit/map", action: :map_edit
      post "patch"
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    get "/photos(/page/:page)" => "images#index", page: /[^0]\d*/,
      constraints: { format: "html" }
  end

  scope "(:locale)", locale: /en|ru/ do
    get "/photos/multiple_species" => "images#multiple_species"
    get "photos/:id" => "images#show", as: "localized_image"
    get "/videos(/page/:page)" => "videos#index", page: /[^0]\d*/,
      constraints: { format: "html" }
    get "videos/:id" => "videos#show", as: "localized_video"
    post "media/strip" => "media#strip"
  end

  scope "(:locale)", locale: /en|ru/ do
    constraints year: /20\d\d/ do
      get "/:year" => "blog#year", as: "year"
      constraints month: /(0[1-9])|(1[0-2])/ do
        get "/:year/:month" => "blog#month", as: "month"
        get "/:year/:month/:id" => "posts#show", as: "show_post"
      end
    end
    get "/archive" => "blog#archive"
  end

  direct :public_post do |blogpost, options|
    route_for(:show_post, options.merge(year: blogpost.year, month: blogpost.month, id: blogpost.to_param))
  end

  direct :public_comment do |comment, options|
    comment.public_send(:post).yield_self do |blogpost| # rubocop:disable Style/SendWithLiteralMethodName
      route_for(:show_post, options.merge(year: blogpost.year, month: blogpost.month, id: blogpost.to_param, anchor: "comment#{comment.id}"))
    end
  end

  direct :localize do |obj, options|
    case obj
    when Image
      route_for(:localized_image, options.merge(id: obj.to_param))
    when Video
      route_for(:localized_video, options.merge(id: obj.to_param))
    when Species
      route_for(:localized_species, options.merge(id: obj.to_param))
    else
      obj # May be string
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    get "/lifelist/overview" => "lifelist#index", as: :lists_overview

    get "/lifelist/advanced" => "lifelist#advanced", as: :advanced_list

    get "/lifelist/winter" => "lifelist#winter", as: :winter_list

    get "/lifelist/stats" => "lifelist#stats"

    get "/lifelist/ebird" => "lifelist#ebird"

    get "/lifelist/chart" => "lifelist#chart"

    get "/lifelist" => "lifelist#basic", as: :lifelist

    get "/lifelist(/:locus)(/:year)(/:sort)" => "lifelist#basic", as: :list,
      locus: %r{(?!by_)\D[^/]+}, # negative look-ahead: not starting with 'by_'
      year: /\d{4}/,
      sort: /by_taxonomy/
  end

  get "/blog.:format" => "feeds#blog", constraints: { format: "xml" }
  get "/instant_articles(.:dev).:format" => "feeds#instant_articles", constraints: { format: "xml", dev: "dev" }
  scope "(:locale)", locale: /en|ru/ do
    get "/photos.:format" => "feeds#photos", constraints: { format: "xml" }
  end
  get "/sitemap.:format" => "feeds#sitemap", constraints: { format: "xml" }

  resources :posts, except: [:index, :show] do
    collection do
      get :hidden
      get :facebook
    end
  end

  resources :cards do
    member do
      post :attach
    end
    collection do
      get :import
    end
  end

  resources :days, only: [:index, :show]

  resources :observations, except: [:index, :new, :create, :edit] do
    collection do
      get "search", action: :search, as: "search"
      get "extract"
      get "move"
    end
  end

  resources :blobs, only: [:create, :show]

  scope "/flickr" do
    get "unflickred" => "flickr_photos#unflickred", as: "unflickred_photos"
    get "unused" => "flickr_photos#unused", as: "flickr_unused"
    get "bou_cc" => "flickr_photos#bou_cc", as: "flickr_bou_cc"
    resources :photos, controller: "flickr_photos", as: "flickr_photos" do
      post :search, on: :collection
      post :push_to_storage, on: :member
    end
  end

  resources :loci do
    collection do
      get :public
      post :save_order
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    resources :comments, only: :create
  end

  resources :comments, except: [:new, :create] do
    get :reply, on: :member
    collection do
      get :unsubscribe, to: "comments#unsubscribe_request", as: :unsubscribe_request
      post :unsubscribe, to: "comments#unsubscribe_submit", as: :unsubscribe_submit
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    resource :map, only: [:show]
  end

  resource :map, only: [:edit] do
    get "media" => "maps#media"
    get "observations", on: :collection
    get "global"
    get "loci"
  end

  resources :spots, only: :destroy do
    post :save, on: :collection
  end

  resources :taxa, except: [:new, :create, :destroy] do
    get :search, on: :collection
  end

  resources :ebird_taxa, only: [:index, :show] do
    member do
      post :promote
    end
  end

  get "/settings" => "settings#index"
  post "/settings/save" => "settings#save"

  scope "/media" do
    get "unmapped" => "media#unmapped"
  end

  get "/reports", controller: :reports, action: :index, as: :reports

  reports_actions = %w(environ insights more_than_year topicture this_day uptoday compare by_countries
    stats voices charts month_targets year_contest server_error)
  reports_actions.each do |name|
    get "/reports/#{name}", controller: :reports, action: name
  end

  get "/reports/five_mile_radius" => "reports/five_mile_radius#index"
  post "/reports/five_mile_radius" => "reports/five_mile_radius#update"

  post "/clear_cache" => "reports#clear_cache"

  resources :corrections do
    get :start, on: :member
  end

  get "/login" => "login#new"
  post "/login" => "login#login"

  get "/logout" => "login#logout"

  get "/flickr" => "flickr#index"
  get "/flickr/auth" => "flickr#auth"

  namespace :ebird do
    get "/" => "portal#index"
    resources :submissions, except: [:edit] do
      post :regenerate, on: :member
    end
    resources :imports, only: [:index, :create] do
      collection do
        post :refresh
      end
    end
  end

  constraints ->(request) { request.session[:admin] == true } do
    mount GoodJob::Engine => "/jobs"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace "deflicker" do
    get "/" => "flickers#index"
    post "refresh" => "flickers#refresh"
    post "rematch" => "flickers#rematch"
    delete "/:id" => "flickers#destroy"
    post "/:id/fixed" => "flickers#fixed"
  end

  scope "(:locale)", locale: /en|ru/ do
    get "about" => "pages#show",
      as: :about,
      format: false,
      id: "about"
  end
  scope "(:locale)", locale: /ru/ do
    get "links" => "pages#show",
      as: :links,
      format: false,
      id: "links"
  end
  scope "ru", locale: "ru" do
    get "winter" => "pages#show",
      as: :winter,
      format: false,
      id: "winter"
  end

  namespace :api do
    resources :loci, only: [:index]
    resources :cards, only: [:index]
    resources :observations, only: [:index]
  end

  post "/csp-violation-report-endpoint" => "content_security#report"
end

app/controllers/maps_controller.rb
# frozen_string_literal: true

class MapsController < ApplicationController
  administrative except: [:show, :media]
  localized only: [:show, :media]

  # GET "/map"
  def show
  end

  # GET "/map/edit"
  def edit
    @observation_search = ObservationSearch.new(params[:q])
    @spot = Spot.new(public: true)
  end

  # GET "/map/observations.json"
  def observations
    preload_tables = [{ card: :locus }, { taxon: :species }, :spots, :images]
    json_methods = [:spots]

    observs =
      # TODO: the goal is to avoid loading all observations (thousands!) if all filters are empty
      # Needs refactoring to only take into account meaningful fields (not "exclude subspecies")
      params[:q]&.values&.any?(&:present?) ?
        ObservationSearch.new(params[:q]).observations
          .joins(:card, :taxon)
          .preload(preload_tables)
          .order("cards.observ_date", "cards.locus_id", "taxa.index_num").limit(params[:limit] || 200) :
        []

    respond_to do |format|
      format.json {
        render json:
        { json: observs.as_json(only: :id, methods: json_methods),
          html: render_to_string(partial: "maps/observation", collection: observs, formats: [:html]), }
      }
    end
  end

  # GET "/map/media.json"
  def media
    render json: Media.for_the_map
  end

  def global
  end

  def loci
    render json: Card.joins(:locus).where.not(loci: { lat: nil }).distinct.pluck(:lat, :lon)
  end
end

app/helpers/map_helper.rb
# frozen_string_literal: true

module MapHelper
  def map_enabled
    !Rails.env.test?
  end
end

app/views/maps/_image.html.haml
-# frozen_string_literal: true
%figure<>
  = link_to image_tag(image.thumbnail_variant), image

app/views/maps/_observation.html.haml
-# frozen_string_literal: true
- img_count = observation.images.size

%li{data: {obs_id: observation.id, obs_count: observation.spots.size}}
  %span.mapped_indicator{title: "Is mapped"}
  %div
    = render partial: "observations/short/species_line", locals: {observation: observation}
  %div
    = render partial: "observations/short/when_where_line", locals: {observation: observation}
  - if img_count > 0
    %div.obs_item_photos
      %span.images_count= img_count
      %div.images_popup= render partial: 'maps/image', collection: observation.images

app/views/maps/edit.html.haml
-# frozen_string_literal: true
- javascript AssetsHelper::GMAP_API_URL, 'map_edit'
- @body_class = 'map-page'
-# no_viewport is for very wide pages, e.g. with table
- @no_viewport = true
- stylesheet 'map_edit'

- @page_title = 'Edit Map'

-# %h1= page_header

= simple_form_for @observation_search, url: observations_map_path(format: :json),
                                                           remote: true, method: :get, html: {class: 'search'} do |form|
  = render 'observations/search_fields', form: form

= render 'spots/form'

.map-side-panel
  %ul.obs-list
    -#= render :partial => 'observations/obs_item', :collection => @observations

.mapContainer
  #googleMap{data: {map_enabled: map_enabled, card_kml: @observation_search.load_card&.kml_url}}

app/views/maps/global.html.haml
-# frozen_string_literal: true
- stylesheet 'map'
- @body_class = 'map-page'
- @special_styling = true
-# no_viewport is for very wide pages, e.g. with table
-# @no_viewport = true
- javascript AssetsHelper::GMAP_API_URL, 'map_global'

-# @page_title = t(".title")

-#%div.map-panel
-#  %a.pseudolink.pan(href="#world")= t(".world")
-#  %a.pseudolink.pan(href="#ukraine")= t(".ukraine")
-#  %a.pseudolink.pan(href="#north_america")= t(".north_america")
-#
-#= render partial: 'partials/translated'

.mapContainer
  #googleMap{data: {map_enabled: map_enabled}}

-#.gallery_window{data: {strip_url: media_strip_path}}
-#  .wnd_close
-#    %span.close
-#      %span.fas.fa-times.fa-2x
-#      %span.pseudolink= t(".close")
-#  .gallery_container

app/views/maps/show.html.haml
-# frozen_string_literal: true
- stylesheet 'map'
- @body_class = 'map-page'
- @special_styling = true
-# no_viewport is for very wide pages, e.g. with table
-# @no_viewport = true
- javascript AssetsHelper::GMAP_API_URL, 'map_show'

- @page_title = t(".title")

%div.map-panel
  %a.pseudolink.pan(href="#world")= t(".world")
  %a.pseudolink.pan(href="#ukraine")= t(".ukraine")
  %a.pseudolink.pan(href="#north_america")= t(".north_america")

= render partial: 'partials/translated'

.mapContainer
  #googleMap{data: {map_enabled: map_enabled}}

.gallery_window{data: {strip_url: media_strip_path}}
  .wnd_close
    %span.close
      %span.fas.fa-times.fa-2x
      %span.pseudolink= t(".close")
  .gallery_container