config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|ru/ do
    root to: "blog#home", as: "blog"
  end

  constraints country: /ukraine|usa|united_kingdom|canada|manitoba/ do
    get "/:country/checklist/edit" => "checklist#edit"
    post "/:country/checklist/edit" => "checklist#save"
    scope "(:locale)", locale: /en|ru/ do
      get "/:country" => "countries#gallery", as: "country"
      get "/:country/checklist" => "checklist#show", as: "checklist"
    end
  end

  resources :species, only: [:edit, :update] do
    collection do
      get "admin", action: :index
      get "admin/search", action: :admin_search

      get :review
      get "synonyms" => "synonyms#index"
      patch "synonyms/:id" => "synonyms#update"

      get "splits" => "species_splits#index"
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    resources :species, only: [:show], as: :localized_species do
      get "search", on: :collection
    end
    get "species" => "species#gallery", as: "gallery"
  end

  resources :photos, controller: "images", as: "images", except: [:index, :show] do
    member do
      get "edit/map", action: :map_edit
      post "patch"
    end
    collection do
      post "upload"
    end
  end

  resources :videos, except: [:index, :show] do
    member do
      get "edit/map", action: :map_edit
      post "patch"
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    get "/photos(/page/:page)" => "images#index", page: /[^0]\d*/,
      constraints: { format: "html" }
  end

  scope "(:locale)", locale: /en|ru/ do
    get "/photos/multiple_species" => "images#multiple_species"
    get "photos/:id" => "images#show", as: "localized_image"
    get "/videos(/page/:page)" => "videos#index", page: /[^0]\d*/,
      constraints: { format: "html" }
    get "videos/:id" => "videos#show", as: "localized_video"
    post "media/strip" => "media#strip"
  end

  scope "(:locale)", locale: /en|ru/ do
    constraints year: /20\d\d/ do
      get "/:year" => "blog#year", as: "year"
      constraints month: /(0[1-9])|(1[0-2])/ do
        get "/:year/:month" => "blog#month", as: "month"
        get "/:year/:month/:id" => "posts#show", as: "show_post"
      end
    end
    get "/archive" => "blog#archive"
  end

  direct :public_post do |blogpost, options|
    route_for(:show_post, options.merge(year: blogpost.year, month: blogpost.month, id: blogpost.to_param))
  end

  direct :public_comment do |comment, options|
    comment.public_send(:post).yield_self do |blogpost| # rubocop:disable Style/SendWithLiteralMethodName
      route_for(:show_post, options.merge(year: blogpost.year, month: blogpost.month, id: blogpost.to_param, anchor: "comment#{comment.id}"))
    end
  end

  direct :localize do |obj, options|
    case obj
    when Image
      route_for(:localized_image, options.merge(id: obj.to_param))
    when Video
      route_for(:localized_video, options.merge(id: obj.to_param))
    when Species
      route_for(:localized_species, options.merge(id: obj.to_param))
    else
      obj # May be string
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    get "/lifelist/overview" => "lifelist#index", as: :lists_overview

    get "/lifelist/advanced" => "lifelist#advanced", as: :advanced_list

    get "/lifelist/winter" => "lifelist#winter", as: :winter_list

    get "/lifelist/stats" => "lifelist#stats"

    get "/lifelist/ebird" => "lifelist#ebird"

    get "/lifelist/chart" => "lifelist#chart"

    get "/lifelist" => "lifelist#basic", as: :lifelist

    get "/lifelist(/:locus)(/:year)(/:sort)" => "lifelist#basic", as: :list,
      locus: %r{(?!by_)\D[^/]+}, # negative look-ahead: not starting with 'by_'
      year: /\d{4}/,
      sort: /by_taxonomy/
  end

  get "/blog.:format" => "feeds#blog", constraints: { format: "xml" }
  get "/instant_articles(.:dev).:format" => "feeds#instant_articles", constraints: { format: "xml", dev: "dev" }
  scope "(:locale)", locale: /en|ru/ do
    get "/photos.:format" => "feeds#photos", constraints: { format: "xml" }
  end
  get "/sitemap.:format" => "feeds#sitemap", constraints: { format: "xml" }

  resources :posts, except: [:index, :show] do
    collection do
      get :hidden
      get :facebook
    end
  end

  resources :cards do
    member do
      post :attach
    end
    collection do
      get :import
    end
  end

  resources :days, only: [:index, :show]

  resources :observations, except: [:index, :new, :create, :edit] do
    collection do
      get "search", action: :search, as: "search"
      get "extract"
      get "move"
    end
  end

  resources :blobs, only: [:create, :show]

  scope "/flickr" do
    get "unflickred" => "flickr_photos#unflickred", as: "unflickred_photos"
    get "unused" => "flickr_photos#unused", as: "flickr_unused"
    get "bou_cc" => "flickr_photos#bou_cc", as: "flickr_bou_cc"
    resources :photos, controller: "flickr_photos", as: "flickr_photos" do
      post :search, on: :collection
      post :push_to_storage, on: :member
    end
  end

  resources :loci do
    collection do
      get :public
      post :save_order
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    resources :comments, only: :create
  end

  resources :comments, except: [:new, :create] do
    get :reply, on: :member
    collection do
      get :unsubscribe, to: "comments#unsubscribe_request", as: :unsubscribe_request
      post :unsubscribe, to: "comments#unsubscribe_submit", as: :unsubscribe_submit
    end
  end

  scope "(:locale)", locale: /en|ru/ do
    resource :map, only: [:show]
  end

  resource :map, only: [:edit] do
    get "media" => "maps#media"
    get "observations", on: :collection
    get "global"
    get "loci"
  end

  resources :spots, only: :destroy do
    post :save, on: :collection
  end

  resources :taxa, except: [:new, :create, :destroy] do
    get :search, on: :collection
  end

  resources :ebird_taxa, only: [:index, :show] do
    member do
      post :promote
    end
  end

  get "/settings" => "settings#index"
  post "/settings/save" => "settings#save"

  scope "/media" do
    get "unmapped" => "media#unmapped"
  end

  get "/reports", controller: :reports, action: :index, as: :reports

  reports_actions = %w(environ insights more_than_year topicture this_day uptoday compare by_countries
    stats voices charts month_targets year_contest server_error)
  reports_actions.each do |name|
    get "/reports/#{name}", controller: :reports, action: name
  end

  get "/reports/five_mile_radius" => "reports/five_mile_radius#index"
  post "/reports/five_mile_radius" => "reports/five_mile_radius#update"

  post "/clear_cache" => "reports#clear_cache"

  resources :corrections do
    get :start, on: :member
  end

  get "/login" => "login#new"
  post "/login" => "login#login"

  get "/logout" => "login#logout"

  get "/flickr" => "flickr#index"
  get "/flickr/auth" => "flickr#auth"

  namespace :ebird do
    get "/" => "portal#index"
    resources :submissions, except: [:edit] do
      post :regenerate, on: :member
    end
    resources :imports, only: [:index, :create] do
      collection do
        post :refresh
      end
    end
  end

  constraints ->(request) { request.session[:admin] == true } do
    mount GoodJob::Engine => "/jobs"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace "deflicker" do
    get "/" => "flickers#index"
    post "refresh" => "flickers#refresh"
    post "rematch" => "flickers#rematch"
    delete "/:id" => "flickers#destroy"
    post "/:id/fixed" => "flickers#fixed"
  end

  scope "(:locale)", locale: /en|ru/ do
    get "about" => "pages#show",
      as: :about,
      format: false,
      id: "about"
  end
  scope "(:locale)", locale: /ru/ do
    get "links" => "pages#show",
      as: :links,
      format: false,
      id: "links"
  end
  scope "ru", locale: "ru" do
    get "winter" => "pages#show",
      as: :winter,
      format: false,
      id: "winter"
  end

  namespace :api do
    resources :loci, only: [:index]
    resources :cards, only: [:index]
    resources :observations, only: [:index]
  end

  post "/csp-violation-report-endpoint" => "content_security#report"
end

app/controllers/reports/five_mile_radius_controller.rb
# frozen_string_literal: true

module Reports
  class FiveMileRadiusController < ApplicationController
    administrative

    def index
      candidates_5mr = Rails.cache.read("5mr/candidates") || []
      candidates_removal = Rails.cache.read("5mr/removal") || []
      loci_ids = (candidates_5mr + candidates_removal).pluck(:locus_id)
      loci = Locus.where(id: loci_ids).index_by(&:id)
      @candidates_5mr = candidates_5mr
        .select { |rec| !loci[rec[:locus_id]].five_mile_radius }
        .each { |rec| rec[:locus] = loci[rec[:locus_id]] }
        .sort_by { |e| e[:distance] }
      @candidates_removal = candidates_removal
        .select { |rec| loci[rec[:locus_id]].five_mile_radius }
        .each { |rec| rec[:locus] = loci[rec[:locus_id]] }
        .sort_by { |e| e[:distance] }
    end

    def update
      locs = params[:locus_id]
      approve = if params[:commit] == "Confirm"
        true
      elsif params[:commit] == "Remove"
        false
      else
        raise "Invalid commit action"
      end
      Locus.where(id: locs).update_all(five_mile_radius: approve)
      Quails::CacheKey.lifelist.invalidate
      redirect_to reports_five_mile_radius_path
    end
  end
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
  def reports_page_header
    capture do
      concat link_to("Reports", reports_path)
      concat " : "
      concat @page_title
    end
  end

  def locus_check(loc)
    content_tag(:span, "", class: "fas fa-check green-check", title: loc, alt: loc)
  end
end

app/views/reports/by_countries.html.haml
-# frozen_string_literal: true
- @page_title = 'Species by number of countries'

%h1= reports_page_header

- @result.each do |num, species|
  %h2= "Seen in #{num} countries (#{species.size} species)"
  - if num > 1
    %ul
      - species.each do |sp_id, _|
        %li
          - sp = @species[sp_id]
          = species_link(sp)
          = name_sci(sp)

app/views/reports/charts.html.haml
-# frozen_string_literal: true
- javascript 'charts'

- @page_title = "Charts"

%h1= reports_page_header

= render partial: 'filters/loci', locals: {loci_filter_label: 'Countries:'}

%div#chartContainer{style: "height: 500px; width: 100%;", data: {series: @data.to_json}}

app/views/reports/compare.html.haml
-# frozen_string_literal: true
-# no_viewport is for very wide pages, e.g. with table
- @no_viewport = true

- @page_title = 'Compare two regions'
- i = 0

%h1= reports_page_header

%ul.horiz-list.filter-list
  %li= link_to('Kyiv / Brovary', {loc1: 'kyiv', loc2: 'brovary'})
  %li= link_to('Kyiv obl / Kherson obl', {loc1: 'kiev_obl', loc2: 'kherson_obl'})
  %li= link_to('Kyiv obl / Ukraine', {loc1: 'kiev_obl', loc2: 'ukraine'})
  %li= link_to('Ukraine / USA', {loc1: 'ukraine', loc2: 'usa'})
  %li= link_to('USA / Canada', {loc1: 'usa', loc2: 'canada'})

%table.neat_table
  %tr
    %th.align-right No
    %th Scientific name
    %th.align-center
      = name1 = @loc1.name
      %br
      (#{@loc1_species.size})
    %th.align-center
      = name2 = @loc2.name
      %br
      (#{@loc2_species.size})

  - @species.group_by_taxonomy do |order, family, species_list|
    %tr
      %td
      %td{:colspan => 3}
        %h2.order= render partial: 'species/taxonomy', locals: {rank: :order, value: order}
        %h3.family= render partial: 'species/taxonomy', locals: {rank: :family, value: family}
    - species_list.each do |species|
      %tr
        %td.align-right= i += 1
        %td
          = species_link(species)
          = name_sci(species)
        %td.align-center= locus_check(name1) if species.in?(@loc1_species)
        %td.align-center= locus_check(name2) if species.in?(@loc2_species)

app/views/reports/environ.html.haml
-# frozen_string_literal: true
- @page_title = 'Environment'

%h1= page_title

%table.neat_table
  %tbody
    %tr
      %th Ruby version
      %td= RUBY_DESCRIPTION

    %tr
      %th Rubygems version
      %td= Gem::VERSION

    %tr
      %th Bundler version
      %td= Bundler::VERSION

    %tr
      %th Rails version
      %td= Rails.version

    %tr
      %th Rack release
      %td= Rack.release

    - request.env['SERVER_SOFTWARE'].if_present do |server_software|
      %tr
        %th Server Software
        %td= server_software

    %tr
      %th Rails Environment
      %td= Rails.env

    %tr
      %th Quails Environment
      %td= Quails.env

    %tr
      %th Database software version
      %td= @pg_version

    %tr
      %th Collation / ctype
      %td
        = @collate["datcollate"]
        \/
        = @collate["datctype"]

    - ENV["DOCKER_IMAGE"].if_present do |docker_image|
      %tr
        %th Docker image
        %td= docker_image

    - ENV["ACTIVE_BACKEND"].if_present do |active_backend|
      %tr
        %th Active backend
        %td= active_backend

    - Quails.revision.if_present do |revision|
      %tr
        %th Revision
        %td
          = link_to revision.sha[0..7], "https://bitbucket.org/khustochka/quails/commits/#{revision.sha}"
          = simple_format(revision.message)

%h2 Env vars

%table.neat_table
  %tbody
    - ENV.keys.sort.each do |key|
      %tr
        %th= key
        %td
          - if [/secret/i, /passw/i, /_key/i, /token/i, /DATABASE_URL/i, /MYLOC/i].any? { |r| key =~ r }
            %span.new_sp *****
          - else
            = ENV[key]

app/views/reports/index.html.haml
-# frozen_string_literal: true
- @page_title = 'Reports and settings'

%h1= page_header

%h3= link_to('Statistics', action: :stats)

%ul
  %li= link_to('Number of species year to date', {action: :uptoday})
  %li= link_to('Yearly chart', {action: :charts})
  %li= link_to('Species found after more than a year', {action: :more_than_year})
  %li= link_to('Start of year contest', {action: :year_contest})
  %li= link_to('Pictured species stats', {action: :topicture})
  %li= link_to('Species mostly recorded by voice', {action: :voices})
  %li= link_to('Images and posts of this day', {action: :this_day})
  %li= link_to('Compare lists of two regions', {action: :compare})
  %li= link_to('Species by number of countries', {action: :by_countries})
  %li= link_to('Month targets', {action: :month_targets})

%h3 Review tasks:

%ul
  %li= link_to('Bulk review and correct', corrections_path)
  %li= link_to('5MR', reports_five_mile_radius_path)
  %li
    = link_to('Half-mapped media', {controller: :media, action: :unmapped, half: true})
    %b (#{Media.half_mapped.size})
    \/
    = link_to('Unmapped media', {controller: :media, action: :unmapped})
  %li= link_to('Unflickred images', unflickred_photos_path)
  %li= link_to('Unused flickr images', flickr_unused_path)
  %li= link_to('Flickr "Birds of Ukraine" photos with CC license', flickr_bou_cc_path)
  %li= link_to('Flickr search', flickr_path)
  %li= link_to('Posted as Facebook instant articles', facebook_posts_path)

%h3
  = link_to('Environment', action: :environ)
  &bull;
  = link_to('DB Insights', action: :insights)
  &bull;
  = link_to('Settings', settings_path)
  &bull;
  = link_to('Clear cache', clear_cache_path, method: :post)

%ul
  %li= link_to('Intentionally produced Server Error', reports_server_error_path)

app/views/reports/insights.html.haml
-# frozen_string_literal: true
- @page_title = 'Insights'

%h1= page_title

%div.fluid-row

  %div.fluid-column

    %h3 Counts

    %ul
      %li
        Posts: #{Post.count}
        %ul.no-margin-list
          %li public: #{Post.public_posts.count}
          %li indexable: #{@index_posts}
      %li
        Approved comments: #{@comments}
        %ul.no-margin-list
          %li not by admin: #{@user_comments}
      %li
        Images: #{Image.count}
        %ul.no-margin-list
          %li indexable: #{@index_images}
      %li Cards: #{Card.count}
      %li Observations: #{Observation.count}
      %li Spots: #{Spot.count}
      %li Indexed species: #{@index_species}
      %li
        %b
          Total indexable (posts + images + species):
          = @index_posts + @index_images + @index_species

app/views/reports/month_targets.html.haml
-# frozen_string_literal: true
- months = t("date.month_names", locale: :en)
- @page_title = "Month targets for #{months[@month]}"
- if @locus
  - @page_title << " (#{@locus.name_en})"

%h1= page_header

%ul.horiz-list.filter-list
  %strong= t('lifelist.menus.filter.months')
  %li= filtering_link_to_all(:month)
  - 1.upto(12) do |m|
    %li
      = link_to_or_span(t("date.abbr_month_names", locale: :en)[m], params.merge(:month => m))


= render partial: 'filters/loci', locals: {loci_filter_label: "Locations:"}

%h3
  Species found in
  = @prev_and_next.map{|m| months[m]}.join(" and ")
  but not in
  = months[@month]

%ol
  - @species.group_by_taxonomy do |order, family, species_list|
    %h2.order= render partial: 'species/taxonomy', locals: {rank: :order, value: order}
    %h3.family= render partial: 'species/taxonomy', locals: {rank: :family, value: family}
    - species_list.each do |sp|
      %li
        = species_link(sp)
        = name_sci(sp)

app/views/reports/more_than_year.html.haml
-# frozen_string_literal: true
-# no_viewport is for very wide pages, e.g. with table
- @no_viewport = true

- @page_title = "Species found after #@period days"

%h1= reports_page_header

%table.neat_table
  %th Species
  %th= sorting_link_to(:date1, "Last encounter")
  %th= sorting_link_to(nil, "Found again")
  %th= sorting_link_to(:days, "Days")

  - @list.each do |el|
    %tr
      %td= species_link(el[:sp])
      %td= link_to el[:date1], day_path(el[:date1])
      %td= link_to el[:date2], day_path(el[:date2])
      %td.align-right= el[:days]

app/views/reports/stats.html.haml
-# frozen_string_literal: true
-# no_viewport is for very wide pages, e.g. with table
- @no_viewport = true

- @page_title = 'Statistics'

%h1= reports_page_header

= render 'filters/years'

= render partial: 'filters/loci', locals: {loci_filter_label: 'Countries:'}

%table.neat_table.statistics
  %tr
    %th Year
    %th Observ
    %th Days
    %th Species
    %th Lifers

  - @year_data.each do |row|
    %tr
      %td= row.year
      %td= row.count_obs
      %td= row.count_days
      %td= row.count_species
      %td= @first_sp_by_year[row.year] rescue nil

%p
  eBird eligible cards this year:
  %b.stats_num= @ebird_eligible_this_year

%table.neat_table.statistics
  %tr
    %th Month
    %th Observ
    %th Species
    %th Lifers

  - (1..12).each do |month|
    %tr
      - @month_data[month].tap do |row|
        %td= t('date.month_names')[month.to_i]
        %td= row.count_obs rescue 0
        %td= row.count_species rescue 0
        %td= @first_sp_by_month[row.month] rescue nil

%h2 Рекордные дни

%h3
  %i — По количеству наблюдений за день

%table.neat_table.statistics
  %tr
    %th Date
    %th Observations
    %th Locations

  - @day_by_obs.each do |row|
    %tr
      %td.nowrap= link_to l(row.observ_date, format: :long), day_path(row.observ_date)
      %td= row.count_obs
      %td= @locs_for_day_by_obs[row.observ_date].map {|c| c.locus.short_name}.join(", ")

%h3
  %i — По количеству видов за день

%table.neat_table.statistics
  %tr
    %th Date
    %th Species count
    %th Locations

  - @day_by_species.each do |row|
    %tr
      %td.nowrap= link_to l(row.observ_date, format: :long), day_path(row.observ_date)
      %td= row.count_species
      %td= @locs_for_day_by_species[row.observ_date].map {|c| c.locus.short_name}.join(", ")

%h3
  %i — По количеству видов в одной местности

%table.neat_table.statistics
  %tr
    %th Date
    %th Species count
    %th Location

  - @day_and_loc_by_species.each do |row|
    %tr
      %td.nowrap= link_to l(row.observ_date, format: :long), day_path(row.observ_date)
      %td= row.count_species
      %td= @preloaded_locs[row.locus_id].short_name

%h3
  %i — По количеству новых видов за день

%table.neat_table.statistics
  %tr
    %th Date
    %th Lifers
    %th Locations

  - (@day_by_new_species || []).each do |row|
    %tr
      %td.nowrap= link_to l(row.observ_date, format: :long), day_path(row.observ_date)
      %td= row.count_species
      %td= @locs_for_day_by_new_species[row.observ_date].map {|c| c.card.locus.short_name}.join(", ")

app/views/reports/this_day.html.haml
-# frozen_string_literal: true
- @page_title = 'Images and posts of the day'

%h1= reports_page_header

%h2= sprintf("%s %s", t("date.month_names")[@month.to_i], @day)

%p
  = link_to("<< previous #@prev_day", {:day => @prev_day}) if @prev_day
  = precede ' | ' do
    = link_to("next #@next_day >>", {:day => @next_day}) if @next_day

- @images.each do |img|
  %h3= link_to img.decorated.title, image_path(img)
  %p
    %i= img.species.map(&:name_sci) * ', '
  %p= image_tag(jpg_url(img))
  %p
    = succeed ", " do
      = link_to l(img.observ_date, :format => :long), day_path(img.observ_date)
    = img.locus.decorated.short_full_name

app/views/reports/topicture.html.haml
-# frozen_string_literal: true
- @page_title = 'Species to take pictures of'

%h1= reports_page_header

%p
  Species with media:
  %b= @species_with_media

%div
  %div.column_layout
    %h2 No pictures at all

    %table.neat_table
      %th &nbsp;
      %th Species
      %th Observations

      - @no_photo.each_with_index do |sp, i|
        %tr
          %td.align-right= "#{i+1}."
          %td= species_link(sp)
          %td.align-right= sp.cnt

  %div.column_layout
    %h2 Latest new species pictured

    %table.neat_table
      %th &nbsp;
      %th Species
      %th Add date

      - @new_pics.each_with_index do |sp, i|
        %tr
          %td.align-right= "#{i+1}."
          %td= species_link(sp)
          %td.align-right= sp.add_date

%div
  %div.column_layout
    %h2 Long time no photo

    %table.neat_table
      %th &nbsp;
      %th Species
      %th Last photo taken

      - @long_time.each_with_index do |sp, i|
        %tr
          %td.align-right= "#{i+1}."
          %td= species_link(sp)
          %td.align-right= sp.lastphoto


  %div.column_layout
    %h2 Latest pictured after > 2yrs

    %table.neat_table
      %th &nbsp;
      %th Species
      %th Last photo
      %th Photo again

      - @recent_2yrs.each_with_index do |el, i|
        %tr
          %td.align-right= "#{i+1}."
          %td= species_link(el[:sp])
          %td= el[:date1]
          %td= el[:date2]

app/views/reports/uptoday.html.haml
-# frozen_string_literal: true
- @page_title = 'Number of species year to date'

%h1= reports_page_header

= render partial: 'filters/loci', locals: {loci_filter_label: 'Countries:'}

%h2
  = link_to "<", day: @prev_day.strftime("%m-%d"), locus: params[:locus]
  = l(@this_day, format: :long)
  = link_to ">", day: @next_day.strftime("%m-%d"), locus: params[:locus]

= render partial: @cell, locals: { include_lifers: false, highlight_max: true }

app/views/reports/voices.html.haml
-# frozen_string_literal: true
- @page_title = 'Species mostly recorded by voice'

%h1= reports_page_header

%p
  - if @exclude_low_num
    = link_to "Include low number species", exclude_low_num: nil
  - else
    = link_to "Exclude low number species", exclude_low_num: true

%table.neat_table
  %tr
    %th
    %th Species
    %th
    %th Voice / Total
  - @species.each_with_index do |sp, i|
    %tr
      %td.align-right= "#{i+1}."
      %td
        = species_link(sp)
      %td.align-right
        %i= sprintf "%.2f" % sp.percentage.to_f
        \%
      %td.align-right
        %small
          = sp.voicenum
          \/
          = sp.totalnum

%h2 By month

%table.neat_table
  %tr
    %th Month
    %th
    %th Voice / Total

  - @month_data.each do |row|
    %tr
      %td= t('date.month_names')[row.month.to_i]
      %td.align-right
        %i= sprintf "%.2f" % row.percentage.to_f
        \%
      %td.align-right
        %small
          = row.voicenum
          \/
          = row.totalnum

app/views/reports/year_contest.html.haml
-# frozen_string_literal: true
- @page_title = "Year start contest"

%h1= reports_page_header

= render partial: "filters/years"

%h2 Year #{@year}

- if @result == []
  %p No species.
- else
  %ol
    - @result.each do |species|
      %li
        = species_link(species)
        = name_sci(species)